### ISSUE TITLE
CLI模式下M方法数据库链接错误

### ISSUE THREAD

**Issue by xiakangdev** [liu21st/extend#34]
如：

``` php
$mode = M('myfriends', null, 'friends_db');
```

配置文件friends_db没有问题，但该方法会报数据库链接错误。

经过调试发现是CLI模式下`DB::parseConfig`方法有问题，对比常规模式下的`DB::parseConfig`，该方法没有对`$db_config`不为空时的数组`key`名进行转换。

**Comment by programer2012** [comment]
如果调用2次 
$this->m_xx = M(‘xx');
$this->m_xxx = M('xxx', NULL, C('DB_xx'));
第二次调用的实例化就会出错 ，依然是到第一次调用的数据库连接找表，所以报table找不到
